---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sky-devops-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
      - name: ravi-docker-registry
      containers:
      - name: skydevops-container
        image: ravirekha1/skydevopsapp:7
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

----

apiVersion: v1
kind: Service
metadata:
 name: my-skydevops-service
 labels:
   app: my-app
spec:
 type: NodePort
 ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30018
 selector:
   app: my-app

...
